### ISSUE TITLE
export { name1 as default } gets exported as variable with the name "default"

### ISSUE THREAD

**Issue by luczsoma** [FTSRG/codemodel-rifle#2]
When exporting from *exporter.js* with the syntax `export { name1 as default }` then *name1* should be the default export of the module. Instead, it gets exported as an ordinary variable with the name "default". This is most possibly a Shift Parser bug.

**Comment by steindani** [comment]
Great question, I did not find any clarification in the specification [http://www.ecma-international.org/ecma-262/6.0/#sec-exports](http://www.ecma-international.org/ecma-262/6.0/#sec-exports). In my opinion Shift is only giving you the syntax tree and it is a semantic information that this is the same as an `export default` statement. This may be a _default_ (hah!) transformation of our framework.

**Comment by luczsoma** [comment]
Thanks for the elaboration. I close this issue, as the "bug" (which is not a bug as is turns out) can be easily resolved by simply adding disposable semantic information to the transformation. I have already done that in commit [c68e331](https://github.com/FTSRG/codemodel-rifle/commit/c68e3311e1f536d4275de1f68c5727c2f6ffcbf2).
