### ISSUE TITLE
IDs should be indexed to speed up setting node relationships at repository sync

### ISSUE THREAD

**Issue by luczsoma** [FTSRG/codemodel-rifle#5]
Node IDs should be indexed, so setting relationships among (very much) ASG-nodes would be faster.

Neo4j provides [a way to create indices on arbitrary properties](http://neo4j.com/docs/developer-manual/current/cypher/schema/index/), but they are not immediately available, but are created in the background:

```Cypher
CREATE INDEX ON :Node(id)
```

The syntax also suggests to append the `Node` label to every ASG-node, so they can be ID-indexed alike.

The ImpermanentGraphDatabase is created on-the-run, so we do not have the time for the index to be created in the background. Searching for a solution to create an "immediate" index for an empty database.

**Comment by szarnyasg** [comment]
I would not bother - ingraph does have a built-in indexer, so it will be plenty fast for this. Once it's done :-).
